config/routes.rb
Rails.application.routes.draw do

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

scope '/upload' do
	resources :photo_records, only: [:destroy]
    resources :events, only: [:update, :edit, :show, :destroy]
    resources :group_admins, only: [:destroy]
    # resources :group_admins
    resources :groups
    devise_for :users

	get '/', to: 'groups#index'
    get '/groups/add_admin/:id' , to: 'groups#new_admin', as: 'new_admin'
    post '/groups/add_admin/:id' , to: 'groups#add_admin', as: 'add_admin'
    get '/groups/new_album/:id' , to: 'groups#new_event', as: 'new_event'
    post '/groups/add_album/:id' , to: 'groups#add_event', as: 'add_event'
    get '/album/:id' , to: 'events#new_upload', as: 'new_upload'
    post '/album/:id' , to: 'events#add_upload', as: 'add_upload'
end


  get '/', to: "gallery#index", as: 'gallery'
  get '/e/:id/:event_name', to: "gallery#event", as: 'gallery_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :events , dependent: :destroy
	has_many :group_admins , dependent: :destroy
	has_many :users , through: :group_admins

	def check_access(user)
		user.isSuperAdmin or !GroupAdmin.find_by(group_id: id,user_id: user.id).nil?
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, except: [:index,:new,:create]
  before_action :check_access, except: [:create,:new,:index]
  before_action :check_super_access, only: [:create,:new, :destroy]


  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @events = @group.events
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def add_admin
	  params[:emails].split(',').each do |email|
	      email = email.strip
        # email = email[0..email.length-5]
	      user = User.find_by(email: email)
        puts email
	      if !user.nil?
	        GroupAdmin.where(group_id:@group.id,user_id:user.id).first_or_create
	      end
      end

	  respond_to do |format|
	 format.html { redirect_to @group, notice: 'Group Admins have been added '}
   end
  end

  def new_event
	  @event = Event.new
  end

  def add_event

	  @event = Event.new(event_params)
	  @event.group_id = @group.id

      respond_to do |format|
        if @event.save
          format.html { redirect_to @event, notice: 'Event was successfully created.' }
          format.json { render :show, status: :created, location: @event }
        else
          format.html { render :new }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end

	 #  respond_to do |format|
	 # format.html { redirect_to @event, notice: 'Event has been created '}

  end

  def new_admin
  end



  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
      @group.destroy
      respond_to do |format|
        format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
    def check_super_access
      if !current_user.isSuperAdmin
  		  render plain: "Access Restricted" and return
  	  end
    end
    def check_access
      if !@group.check_access(current_user)
  		  render plain: "Access Restricted" and return
  	  end
    end

	def event_params
    	params.require(:event).permit(:group_id, :name, :description)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @group.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h4>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="page-header">
  <%= link_to groups_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @group, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing group</h1>
</div>

<%= render 'form' %>

app/views/groups/index.html.erb
<div class="page-header">
 <% if current_user.isSuperAdmin %>
  <%= link_to new_group_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Group
  <% end %>
 <% end %>

  <h1>Listing groups</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
		<% if current_user.isSuperAdmin %>
      <%= content_tag_for(:tr, @groups) do |group| %>
            <td><%= group.name %></td>
            <td><%= group.description %></td>
            <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <!-- <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <td><a href="<%= add_admin_path(group) %>" >Add Admin</a></td>
      <% end %>
      <% else %>
		  <%= content_tag_for(:tr, current_user.groups) do |group| %>
				<td><%= group.name %></td>
				<td><%= group.description %></td>
				<td><%= link_to 'Show', group %></td>
			<td><%= link_to 'Edit', edit_group_path(group) %></td>
			<!-- <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
			<td><a href="<%= add_admin_path(group) %>" >Add Admin</a></td>
		  <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="page-header">
  <%= link_to groups_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New group</h1>
</div>

<%= render 'form' %>

app/views/groups/new_admin.html.erb
<div class="page-header">
  <%= link_to group_path(@group), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Admin</h1>
</div>

<%= form_tag({:action => :add_admin},class: "form-horizontal", onsubmit:"before_submit()", id:"mailForm", method: :post, multipart: true)do %>
        <!-- <p id="email_id">Emails: <%= text_field_tag :emails %></p>
        <div><%= submit_tag 'Add' ,class: "btn"%> -->
	  <div class="form-group">
	    <label class="col-sm-2 control-label" for="emails">Emails</label>
	    <div class="col-sm-10">
	      <input class="form-control" type="text" name="emails" id="emails" />
	    </div>
	  </div>
	  <div class="form-group">
	    <div class="col-sm-offset-2 col-sm-10">
	      <input type="submit" name="commit" value="Add Admins" class="btn btn-primary" data-disable-with="Add Admins" />
	    </div>
	  </div>
<% end %>

app/views/groups/new_event.html.erb
<div class="page-header">
  <%= link_to group_path(@group), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Album</h1>
</div>

<%= form_for( @event, url: add_event_path(@group), html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="form-group">
    <%= f.label :group, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :group, class: "form-control" %>
    </div>
  </div> -->
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<div class="page-header">
  <%= link_to groups_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_group_path(@group), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%=@group.name%></h1>
</div>

<dl class="dl-horizontal">
  <!-- <dt>Name:</dt>
  <dd><%= @group.name %></dd> -->

  <dt>Description:</dt>
  <dd><%= @group.description %></dd>

  <div class="page-header">
    <%= link_to new_admin_path(@group), class: 'btn btn-primary' do %>
  	<span class="glyphicon glyphicon-plus"></span>
  	New Admin
    <% end %>
    <h3>Listing Admins</h3>
  </div>

  <table class="table table-striped table-bordered table-hover">
    <thead>
  	<tr>
  		  <th>Email</th>
  		  <th>Remove</th>
  		  <!-- <th></th>
  	  <th></th>
  	  <th></th> -->
  	</tr>
    </thead>

    <tbody>
  	<%= content_tag_for(:tr, @group.group_admins) do |group_admin| %>
  		  <td><%= group_admin.user.email %></td>
		  <td><%= link_to 'Remove', group_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  	<% end %>
    </tbody>
  </table>

  <div class="page-header">
    <%= link_to new_event_path(@group), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Album
    <% end %>
    <h3>Listing Albums</h3>
  </div>
</br>


<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <!-- <th>Group</th> -->
            <th>Name</th>
            <th>Description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @events) do |event| %>
            <!-- <td><%= event.group %></td> -->
            <td><%= event.name %></td>
            <td><%= event.description %></td>
            <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>



</dl>