config/routes.rb
Rails.application.routes.draw do

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

scope '/upload' do
	resources :photo_records, only: [:destroy]
    resources :events, only: [:update, :edit, :show, :destroy]
    resources :group_admins, only: [:destroy]
    # resources :group_admins
    resources :groups
    devise_for :users

	get '/', to: 'groups#index'
    get '/groups/add_admin/:id' , to: 'groups#new_admin', as: 'new_admin'
    post '/groups/add_admin/:id' , to: 'groups#add_admin', as: 'add_admin'
    get '/groups/new_album/:id' , to: 'groups#new_event', as: 'new_event'
    post '/groups/add_album/:id' , to: 'groups#add_event', as: 'add_event'
    get '/album/:id' , to: 'events#new_upload', as: 'new_upload'
    post '/album/:id' , to: 'events#add_upload', as: 'add_upload'
end


  get '/', to: "gallery#index", as: 'gallery'
  get '/e/:id/:event_name', to: "gallery#event", as: 'gallery_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
  has_many :photo_records , dependent: :destroy

  after_commit :clearCache

  def clearCache
	  Event.all.each do |event|
		 ActionController::Base.expire_page(Rails.application.routes.url_helpers.gallery_event_path id:event.id,event_name: event.name)
	  end
	  ActionController::Base.expire_page(Rails.application.routes.url_helpers.gallery_path)
  end

  def check_access(user)
	  self.group.check_access(user)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :add_upload,:new_upload]
  before_action :check_access

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  def new_upload
  end

  def add_upload
	  stored_files = {files: []}
	  params["files"].each do |file|
		  a = PhotoRecord.new(user_id:current_user.id,event_id:@event.id)
		  a.photo = file
		  a.save!
		  # stored_files.files.push(file.name)
	  end
	  flash[:success] = 'Photos were successfully uploaded and are processing in the background. It might take a while for you to see it.'
	  # format.html {  notice: 'Photos were successfully uploaded and are processing in the background. It might take a while for you to see it.' }
	  render json: stored_files

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  # def create
  #   @event = Event.new(event_params)
  #
  #   respond_to do |format|
  #     if @event.save
  #       format.html { redirect_to @event, notice: 'Event was successfully created.' }
  #       format.json { render :show, status: :created, location: @event }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @event.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
	group_id = @event.group_id
    @event.destroy
    respond_to do |format|
      format.html { redirect_to group_path(group_id), notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description)
    end

	def check_access
      if !@event.check_access(current_user)
  		  render plain: "Access Restricted" and return
  	  end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h4>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <%= link_to group_path(@event.group_id), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @event, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing event</h1>
</div>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="page-header">
  <%= link_to new_event_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Event
  <% end %>
  <h1>Listing events</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Group</th>
            <th>Name</th>
            <th>Description</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @events) do |event| %>
            <td><%= event.group %></td>
            <td><%= event.name %></td>
            <td><%= event.description %></td>
            <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/new.html.erb
<div class="page-header">
  <%= link_to events_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New event</h1>
</div>

<%= render 'form' %>

app/views/events/new_upload.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!-- Generic page styles -->
<link rel="stylesheet" href="/css/style.css">
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->
<link rel="stylesheet" href="/css/jquery.fileupload.css">
</head>
<body>
<div class="container">

	<div class="page-header">
	  <%= link_to event_path(@event), class: 'btn btn-default' do %>
	    <span class="glyphicon glyphicon-list-alt"></span>
	    Back
	  <% end %>
	  <h1><%= @event.name %></h1>
	</div>
    <!-- <h1>jQuery File Upload Demo</h1> -->
    <!-- <h2 class="lead">Basic version</h2> -->
    <!-- <ul class="nav nav-tabs">
        <li class="active"><a href="basic.html">Basic</a></li>
        <li><a href="basic-plus.html">Basic Plus</a></li>
        <li><a href="index.html">Basic Plus UI</a></li>
        <li><a href="angularjs.html">AngularJS</a></li>
        <li><a href="jquery-ui.html">jQuery UI</a></li>
    </ul> -->
    <!-- <br>
    <blockquote>
        <p>File Upload widget with multiple file selection, drag&amp;drop support and progress bar for jQuery.<br>
        Supports cross-domain, chunked and resumable file uploads.<br>
        Works with any server-side platform (PHP, Python, Ruby on Rails, Java, Node.js, Go etc.) that supports standard HTML form file uploads.</p>
    </blockquote>
    <br> -->
    <!-- The fileinput-button span is used to style the file input field as button -->
    <span class="btn btn-success fileinput-button">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Select files...</span>
        <!-- The file input field used as target for the file upload widget -->
        <input id="fileupload" type="file" name="files[]" multiple>
    </span>
    <br>
    <br>
    <!-- The global progress bar -->
    <div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
    </div>
    <!-- The container for the uploaded files -->
    <div id="files" class="files"></div>
    <br>
	<blockquote>
        <p>Please upload responsibly. This is not for archival purposes. Full resolution images are not stored. Upload only images: "jpg/png/jpeg/gif" </p>
    </blockquote>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Instructions and Tips</h3>
        </div>
        <div class="panel-body">

            <ul>
                <li>Preferably upload images of less than <strong>3 MB</strong> .</li>
                <li>Only image files (<strong>JPG, GIF, PNG</strong>) are allowed .</li>
                <li>Uploaded files will be downscaled to two resolutions</li>
				<li>High-Resolution : maximum dimension as <strong>2000px</strong></li>
				<li>Thumbnail :  Dimension are <strong>200 X 200 px</strong></li>
                <li>You can <strong>drag &amp; drop</strong> files from your desktop on this webpage. </li>
                <!-- <li>Please refer to the <a href="https://github.com/blueimp/jQuery-File-Upload">project website</a> and <a href="https://github.com/blueimp/jQuery-File-Upload/wiki">documentation</a> for more information.</li> -->
                <!-- <li>Built with the <a href="http://getbootstrap.com/">Bootstrap</a> CSS framework and Icons from <a href="http://glyphicons.com/">Glyphicons</a>.</li> -->
            </ul>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/js/vendor/jquery.ui.widget.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<!-- <script src="https://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script> -->
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<!-- <script src="https://blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script> -->
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="/js/jquery.fileupload.js"></script>
<!-- The File Upload processing plugin -->
<!-- <script src="/js/jquery.fileupload-process.js"></script> -->
<!-- The File Upload image preview & resize plugin -->
<!-- <script src="/js/jquery.fileupload-image.js"></script> -->

<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script>
/*jslint unparam: true */
/*global window, $ */

// $("<input>", {
// 			  type: 'hidden',
// 			  name: 'authenticity_token',
// 			  value: $('meta[name="csrf-token"]').attr('content')
// 		  })
//
$(window).on('load', function() {
	$(function () {

	    'use strict';
	    // Change this to the location of your server-side upload handler:
	    var url = "<%= add_upload_path(@event) %>"
	    $('#fileupload').fileupload({

	        url: url,
	        dataType: 'json',
	        done: function (e, data) {
	            $.each(data.result.files, function (index, file) {
	                $('<p/>').text(file.name).appendTo('#files');
	            });

	        },
	        progressall: function (e, data) {
	            var progress = parseInt(data.loaded / data.total * 100, 10);
	            $('#progress .progress-bar').css(
	                'width',
	                progress + '%'
	            );
				if(data.loaded == data.total)
					window.location.replace("<%= event_path(@event) %>");
	        }
	    }).prop('disabled', !$.support.fileInput)
	        .parent().addClass($.support.fileInput ? undefined : 'disabled');
	});
});

</script>

app/views/events/show.html.erb
<div class="page-header">
  <%= link_to group_path(@event.group_id), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_event_path(@event), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @event.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Group:</dt>
  <dd><%= @event.group.name %></dd>

  <dt>Album:</dt>
  <dd><%= @event.name %></dd>

  <dt>Description:</dt>
  <dd><%= @event.description %></dd>


</dl>

<div class="page-header">
  <%= link_to new_upload_path(@event), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  Upload Photos
  <% end %>
  <h3>Listing Photos</h3>
</div>


<div id="links">

	<% @event.photo_records.each do |photo_record| %>
		<!-- <a href="<%=photo_record.photo.url%>" ><img src="<%=photo_record.photo.thumb.url%>" class="remove-padding" alt="<%=@event.name%>"></a> -->

	<div class="img-thumbnail text-center">
	   <a href="<%=photo_record.photo.url%>"  ><img src="<%=photo_record.photo.thumb.url%>" class="remove-padding" alt="<%=@event.name%>"></a>
	   <p style="font-size:10px">
	   Uploaded by <%=photo_record.user.email%>
   	   </p>
	   <%= link_to 'Delete', photo_record, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger btn-xs da'%>
	 </div>
	 <% end%>
</div>