config/routes.rb
Rails.application.routes.draw do

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

scope '/upload' do
	resources :photo_records, only: [:destroy]
    resources :events, only: [:update, :edit, :show, :destroy]
    resources :group_admins, only: [:destroy]
    # resources :group_admins
    resources :groups
    devise_for :users

	get '/', to: 'groups#index'
    get '/groups/add_admin/:id' , to: 'groups#new_admin', as: 'new_admin'
    post '/groups/add_admin/:id' , to: 'groups#add_admin', as: 'add_admin'
    get '/groups/new_album/:id' , to: 'groups#new_event', as: 'new_event'
    post '/groups/add_album/:id' , to: 'groups#add_event', as: 'add_event'
    get '/album/:id' , to: 'events#new_upload', as: 'new_upload'
    post '/album/:id' , to: 'events#add_upload', as: 'add_upload'
end


  get '/', to: "gallery#index", as: 'gallery'
  get '/e/:id/:event_name', to: "gallery#event", as: 'gallery_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo_record.rb
class PhotoRecord < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :event

  after_commit :clearCache

  def clearCache
   ActionController::Base.expire_page(Rails.application.routes.url_helpers.gallery_event_path id:self.event.id,event_name: self.event.name)
   ActionController::Base.expire_page(Rails.application.routes.url_helpers.gallery_path)
  end

end

app/controllers/photo_records_controller.rb
class PhotoRecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo_record, only: [:show, :edit, :update, :destroy]
  before_action :check_access

  # GET /photo_records
  # GET /photo_records.json
  # def index
  #   @photo_records = PhotoRecord.all
  # end

  # GET /photo_records/1
  # GET /photo_records/1.json
  # def show
  # end

  # GET /photo_records/new
  # def new
  #   @photo_record = PhotoRecord.new
  # end

  # GET /photo_records/1/edit
  # def edit
  # end

  # POST /photo_records
  # POST /photo_records.json
  # def create
  #   @photo_record = PhotoRecord.new(photo_record_params)
  #
  #   respond_to do |format|
  #     if @photo_record.save
  #       format.html { redirect_to @photo_record, notice: 'Photo record was successfully created.' }
  #       format.json { render :show, status: :created, location: @photo_record }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @photo_record.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /photo_records/1
  # PATCH/PUT /photo_records/1.json
  # def update
  #   respond_to do |format|
  #     if @photo_record.update(photo_record_params)
  #       format.html { redirect_to @photo_record, notice: 'Photo record was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @photo_record }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @photo_record.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /photo_records/1
  # DELETE /photo_records/1.json
  def destroy
	event_id = @photo_record.event_id
    @photo_record.destroy
    respond_to do |format|
      format.html { redirect_to event_path(event_id), notice: 'Photo record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_record
      @photo_record = PhotoRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def photo_record_params
    #   params.require(:photo_record).permit(:event, :user_id)
    # end

	def check_access
      if !@photo_record.event.check_access(current_user)
  		  render plain: "Access Restricted" and return
  	  end
    end
end

app/helpers/photo_records_helper.rb
module PhotoRecordsHelper
end

app/views/photo_records/_form.html.erb
<%= form_for(@photo_record, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @photo_record.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@photo_record.errors.count, "error") %> prohibited this photo_record from being saved:</h4>

      <ul>
      <% @photo_record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :event, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :event, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/photo_records/edit.html.erb
<div class="page-header">
  <%= link_to photo_records_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @photo_record, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing photo_record</h1>
</div>

<%= render 'form' %>

app/views/photo_records/index.html.erb
<div class="page-header">
  <%= link_to new_photo_record_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Photo record
  <% end %>
  <h1>Listing photo_records</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Event</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @photo_records) do |photo_record| %>
            <td><%= photo_record.event %></td>
            <td><%= photo_record.user %></td>
            <td><%= link_to 'Show', photo_record %></td>
        <td><%= link_to 'Edit', edit_photo_record_path(photo_record) %></td>
        <td><%= link_to 'Destroy', photo_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/photo_records/new.html.erb
<div class="page-header">
  <%= link_to photo_records_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New photo_record</h1>
</div>

<%= render 'form' %>

app/views/photo_records/show.html.erb
<div class="page-header">
  <%= link_to photo_records_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_photo_record_path(@photo_record), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show photo_record</h1>
</div>

<dl class="dl-horizontal">
  <dt>Event:</dt>
  <dd><%= @photo_record.event %></dd>

  <dt>User:</dt>
  <dd><%= @photo_record.user %></dd>

</dl>