config/routes.rb
Rails.application.routes.draw do

mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

scope '/upload' do
	resources :photo_records, only: [:destroy]
    resources :events, only: [:update, :edit, :show, :destroy]
    resources :group_admins, only: [:destroy]
    # resources :group_admins
    resources :groups
    devise_for :users

	get '/', to: 'groups#index'
    get '/groups/add_admin/:id' , to: 'groups#new_admin', as: 'new_admin'
    post '/groups/add_admin/:id' , to: 'groups#add_admin', as: 'add_admin'
    get '/groups/new_album/:id' , to: 'groups#new_event', as: 'new_event'
    post '/groups/add_album/:id' , to: 'groups#add_event', as: 'add_event'
    get '/album/:id' , to: 'events#new_upload', as: 'new_upload'
    post '/album/:id' , to: 'events#add_upload', as: 'add_upload'
end


  get '/', to: "gallery#index", as: 'gallery'
  get '/e/:id/:event_name', to: "gallery#event", as: 'gallery_event'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group_admin.rb
class GroupAdmin < ApplicationRecord
  belongs_to :group
  belongs_to :user

  after_commit :send_mail ,  on: :create

  def send_mail
    Mailer.admin_create_email(self.user,self.group).deliver_later
  end
end

app/controllers/group_admins_controller.rb
class GroupAdminsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group_admin, only: [:destroy]
  before_action :check_access, only: [:destroy]
  #
  # # GET /group_admins
  # # GET /group_admins.json
  # def index
  #   @group_admins = GroupAdmin.all
  # end
  #
  # # GET /group_admins/1
  # # GET /group_admins/1.json
  # def show
  # end
  #
  # # GET /group_admins/new
  # def new
  #   @group_admin = GroupAdmin.new
  # end
  #
  # # GET /group_admins/1/edit
  # def edit
  # end
  #
  # # POST /group_admins
  # # POST /group_admins.json
  # def create
  #   @group_admin = GroupAdmin.new(group_admin_params)
  #
  #   respond_to do |format|
  #     if @group_admin.save
  #       format.html { redirect_to @group_admin, notice: 'Group admin was successfully created.' }
  #       format.json { render :show, status: :created, location: @group_admin }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @group_admin.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /group_admins/1
  # # PATCH/PUT /group_admins/1.json
  # def update
  #   respond_to do |format|
  #     if @group_admin.update(group_admin_params)
  #       format.html { redirect_to @group_admin, notice: 'Group admin was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @group_admin }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @group_admin.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # DELETE /group_admins/1
  # # DELETE /group_admins/1.json
  def destroy
    @group_admin.destroy
	group_id = @group_admin.group_id
    respond_to do |format|
      format.html { redirect_to group_path(group_id), notice: 'Group admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_admin
      @group_admin = GroupAdmin.find(params[:id])
    end

	def check_access
      if !@group_admin.group.check_access(current_user)
  		  render plain: "Access Restricted" and return
  	  end
    end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def group_admin_params
  #     params.require(:group_admin).permit(:group_id, :user_id)
  #   end
end

app/helpers/group_admins_helper.rb
module GroupAdminsHelper
end

app/views/group_admins/_form.html.erb
<%= form_for(@group_admin, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @group_admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@group_admin.errors.count, "error") %> prohibited this group_admin from being saved:</h4>

      <ul>
      <% @group_admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :group, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :group, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/group_admins/edit.html.erb
<div class="page-header">
  <%= link_to group_admins_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @group_admin, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing group_admin</h1>
</div>

<%= render 'form' %>

app/views/group_admins/index.html.erb
<div class="page-header">
  <%= link_to new_group_admin_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Group admin
  <% end %>
  <h1>Listing group_admins</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Group</th>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @group_admins) do |group_admin| %>
            <td><%= group_admin.group %></td>
            <td><%= group_admin.user %></td>
            <td><%= link_to 'Show', group_admin %></td>
        <td><%= link_to 'Edit', edit_group_admin_path(group_admin) %></td>
        <td><%= link_to 'Destroy', group_admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/group_admins/new.html.erb
<div class="page-header">
  <%= link_to group_admins_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New group_admin</h1>
</div>

<%= render 'form' %>

app/views/group_admins/show.html.erb
<div class="page-header">
  <%= link_to group_admins_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_group_admin_path(@group_admin), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show group_admin</h1>
</div>

<dl class="dl-horizontal">
  <dt>Group:</dt>
  <dd><%= @group_admin.group %></dd>

  <dt>User:</dt>
  <dd><%= @group_admin.user %></dd>

</dl>